#!/bin/bash

# Single node setup for Clique PoA!! Doesn't even require a bootnode! Much nicer if resources are limited.
# Almost any kind of connection is allowed since it's a testing environment.

geth --datadir blockchain/node/ --rpc --rpcaddr 'localhost' --rpcapi 'personal,db,eth,net,web3,txpool,miner' --gasprice '1' -unlock 'b7d186b399eab551f9990c677df587a11a77d6e4' --password blockchain/password.txt --mine
